apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xypazr733-python
  janus-idp.io/tekton: xypazr733-python
  backstage.io/kubernetes-id: xypazr733-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xypazr733-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
